[platformio]
default_envs = esp32dev


[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_filters = esp32_exception_decoder
build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D esp32dev=1
    -D CONFIG_COMPILER_OPTIMIZATION_PERF=y
    -D CONFIG_FREERTOS_HZ=1000
    -D HARDWARE_SHA256=1
    -O2

monitor_speed = 115200
upload_speed = 921600

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio

lib_deps =
    bblanchon/ArduinoJson@^7.2.2
    mathertel/OneButton@^2.6.2