[platformio]
default_envs = IdeaSparkESP32

[env:IdeaSparkESP32]
platform = espressif32 @ 6.7.0
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
build_flags = 
    -D IdeaSparkS3=1
    -D LGFX_USE_V1
    -D BOARD_HAS_PSRAM
lib_deps = 
    tzapu/WiFiManager @ ^2.0.17
    mathertel/OneButton@^2.6.2
    arduino-libraries/NTPClient@^3.2.1
    bblanchon/ArduinoJson@^7.2.2
    lovyan03/LovyanGFX @ ^1.1.12
lib_ignore = 
    SD
    TFT_eSPI