[env:ESP32_Touch_LCD_3_5]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.psram = enabled
board_build.arduino.memory_type = qio_qspi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_build.flash_mode = dio
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -D TFT_CS=5
    -D TFT_DC=27
    -D TFT_SCLK=18
    -D TFT_MOSI=23
    -D TFT_MISO=19
    -D TFT_BL=25
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    lovyan03/LovyanGFX @ ^1.1.12